# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_DRM_PANEL_GOOGLE_BIGSURF)		+= panel-google-bigsurf.o
obj-$(CONFIG_DRM_PANEL_GOOGLE_HK3)		+= panel-google-hk3.o
obj-$(CONFIG_DRM_PANEL_GOOGLE_SHORELINE)	+= panel-google-shoreline.o
obj-$(CONFIG_DRM_PANEL_GOOGLE_TK4B)		+= panel-google-tk4b.o
obj-$(CONFIG_DRM_PANEL_GS_CM4)			+= panel-gs-cm4.o
obj-$(CONFIG_DRM_PANEL_GS_KM4)			+= panel-gs-km4.o
obj-$(CONFIG_DRM_PANEL_GS_TK4A)			+= panel-gs-tk4a.o
obj-$(CONFIG_DRM_PANEL_GS_TK4C)			+= panel-gs-tk4c.o
